Fix phase offset of Linkwitz-Riley Allpass Filters and add testing function
sfstoolbox/sfs pull request #185
Opened 2019-03-04 09:48 UTC by fietew

For some filter orders (even, but not divisible by four), there was a wrong sign for LR Allpass Filters. This PR fix this and adds a testing function.

2019-03-04 11:30 UTC, fs446 commented
bug fix seems ok to me, just corrected the labeling of axis in the test script.

2019-03-05 06:33 UTC, hagenw commented
The test runs fine o my machine.
Is this the desired output:
**Fig1**
![fig1](https://user-images.githubusercontent.com/173624/53785451-d5c91180-3f18-11e9-8e59-4471b1327bd4.png)
**Fig 2**
![fig2](https://user-images.githubusercontent.com/173624/53785461-da8dc580-3f18-11e9-9899-e0926270d68b.png)
**Fig 3**
![fig3](https://user-images.githubusercontent.com/173624/53785463-dd88b600-3f18-11e9-8a62-62a3b7e1024e.png)

2019-03-05 06:37 UTC, hagenw requested changes

2019-03-05 06:37 UTC, hagenw commented on validation/test_linkwitz_riley.m
> +% Copyright (c) 2010-2018 SFS Toolbox Developers                             *
Please change `2018` to `2019` as I changed that already in the master.

2019-03-05 06:37 UTC, hagenw commented on validation/test_linkwitz_riley.m
> +fc = 1000;  % crossover frequency
For both please add ` in Hz` at the end of the comment.

2019-03-05 06:37 UTC, hagenw commented on validation/test_linkwitz_riley.m
> +end
Please add a newline at the end.

2019-03-05 09:35 UTC, fietew commented
> Is this the desired output:

It seems, there is a problem regarding the Octave output. The greens lines in Fig1 and Fig3 (upper left) should be horizontal. I will have a look.

2019-03-05 10:17 UTC, fietew commented
The behaviour is, again, related to a bug in zp2sos in Octave (see https://savannah.gnu.org/bugs/?51936), where single or non-existing zeros are handled incorrect. This was already mentioned in #169 . I used a similar workaround for this.

2019-03-05 10:21 UTC, hagenw commented
Looks good now, here are the new figures I'm getting by running the test:
**Fig 1**
![fig1](https://user-images.githubusercontent.com/173624/53798559-c35ed000-3f38-11e9-8c81-6ce829464b2e.png)
**Fig 2**
![fig2](https://user-images.githubusercontent.com/173624/53798565-c8238400-3f38-11e9-8f4b-adbdb0c1116d.png)
**Fig 3**
![fig3](https://user-images.githubusercontent.com/173624/53798572-cc4fa180-3f38-11e9-8bd4-3ff047bbc8bd.png)

2019-03-05 10:21 UTC, hagenw approved these changes

2019-03-05 10:24 UTC, fs446 approved these changes
looks good

2019-03-05 10:29 UTC, hagenw commented
Is it ok to squash the commits during merge?

Alternatively I would propose to condense them to two, one for the fix and one for adding testing functions.

2019-03-08 08:25 UTC, merged